pipeline {
    agent any

    tools {
        maven "MAVENHOME"
        jdk "JAVAHOME"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'f93bcc15-102e-45a6-9c99-665d209e10c0', url: 'https://github.com/SreedeviPK/myRepo1']]])
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
               //  dir("/var/lib/jenkins/workspace/New_demo/my-app") {
              //  sh 'mvn -B -DskipTests clean package'
               // }
            
            }
        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
